version: '3.8'

services:
  frontend:
    image: 01sudharsan/sihfrontend-app:latest
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

  backend:
    image: 01sudharsan/sihbackend-app:latest
    container_name: backend
    ports:
      - "8000:8000"
    restart: always

































